Allow user to specify the device family pack to install
Resolves #18 (Allow user to specify the device family pack to install).

diff --git a/install-device-family-pack b/install-device-family-pack
--- a/install-device-family-pack
+++ b/install-device-family-pack
@@ -15,7 +15,7 @@
 # KIND, either express or implied. See the License for the specific language governing
 # permissions and limitations under the License.
 
-# File: install-device-family-packs
+# File: install-device-family-pack
 # Description: avr-gcc device family pack install script.
 
 function error()
@@ -39,12 +39,14 @@ function abort()
 function display_help_text()
 {
     echo "NAME"
-    echo "    $mnemonic - Install avr-gcc device family packs."
+    echo "    $mnemonic - Install an avr-gcc device family pack."
     echo "SYNOPSIS"
     echo "    $mnemonic --help"
     echo "    $mnemonic --version"
-    echo "    $mnemonic --install-prefix <install-prefix>"
+    echo "    $mnemonic --install-prefix <install-prefix> --family-pack <name> <version>"
     echo "OPTIONS"
+    echo "    --family-pack <name> <version>"
+    echo "        Specify the name and version of the device family pack to install."
     echo "    --help"
     echo "        Display this help text."
     echo "    --install-prefix <install-prefix>"
@@ -54,7 +56,7 @@ function display_help_text()
     echo "EXAMPLES"
     echo "    $mnemonic --help"
     echo "    $mnemonic --version"
-    echo "    $mnemonic --install-prefix ~/bin/avr-gcc/8.3.0"
+    echo "    $mnemonic --install-prefix ~/bin/avr-gcc/8.3.0 --family-pack ATmega 2.0.401"
 }
 
 function display_version()
@@ -64,30 +66,21 @@ function display_version()
 
 function download()
 {
-    case "$family" in
-        atmega)
-            local -r url="http://packs.download.atmel.com/Atmel.ATmega_DFP.1.6.364.atpack"
-            ;;
-        *)
-            abort "'$family' is not a supported family"
-            ;;
-    esac
-
-    if ! ( cd "$build_directory" && wget "$url" -O "$build_directory/$family.zip" ); then
-        abort "$family device family pack download failure"
+    if ! ( cd "$build_directory" && wget "http://packs.download.atmel.com/$family_pack.atpack" ); then
+        abort "device family pack download failure"
     fi
 }
 
 function extract()
 {
-    if ! unzip "$build_directory/$family.zip" -d "$build_directory/$family"; then
-        abort "$family device family pack extraction failure"
+    if ! unzip "$build_directory/$family_pack.atpack" -d "$build_directory/$family_pack"; then
+        abort "device family pack extraction failure"
     fi
 }
 
 function install_device_specs()
 {
-    local device_specs; mapfile -t device_specs < <( find "$build_directory/$family/gcc/dev" -name "specs-*" ); readonly device_specs
+    local device_specs; mapfile -t device_specs < <( find "$build_directory/$family_pack/gcc/dev" -name "specs-*" ); readonly device_specs
 
     local -r install_directory="$( find "$install_prefix/lib/gcc/avr" -type d -name "device-specs" )"
 
@@ -100,7 +93,7 @@ function install_device_specs()
 
 function install_device_startup_files_and_libraries()
 {
-    local devices; mapfile -t devices < <( find "$build_directory/$family/gcc/dev" -mindepth 1 -maxdepth 1 -type d ); readonly devices
+    local devices; mapfile -t devices < <( find "$build_directory/$family_pack/gcc/dev" -mindepth 1 -maxdepth 1 -type d ); readonly devices
 
     for device in "${devices[@]}"; do
         local device_startup_files_and_libraries; mapfile -t device_startup_files_and_libraries < <( cd "$device" && find . -mindepth 1 -maxdepth 1 -type d ! -name "device-specs" )
@@ -116,7 +109,7 @@ function install_device_startup_files_and_libraries()
 
 function install_header_files()
 {
-    local header_files; mapfile -t header_files < <( find "$build_directory/$family/include/avr" -name "*.h" ); readonly header_files
+    local header_files; mapfile -t header_files < <( find "$build_directory/$family_pack/include/avr" -name "*.h" ); readonly header_files
 
     for header_file in "${header_files[@]}"; do
         if ! cp "$header_file" "$install_prefix/avr/include/avr/"; then
@@ -125,7 +118,7 @@ function install_header_files()
     done
 }
 
-function install_device_family_packs()
+function install_device_family_pack()
 {
     local -r build_directory="$repository/build"
 
@@ -135,17 +128,11 @@ function install_device_family_packs()
         abort "build directory creation failure"
     fi
 
-    local -r families=(
-        "atmega"
-    )
-
-    for family in "${families[@]}"; do
-        download
-        extract
-        install_device_specs
-        install_device_startup_files_and_libraries
-        install_header_files
-    done
+    download
+    extract
+    install_device_specs
+    install_device_startup_files_and_libraries
+    install_header_files
 }
 
 function main()
@@ -159,6 +146,24 @@ function main()
         local argument="$1"; shift
 
         case "$argument" in
+            --family-pack)
+                if [[ -n "$family_pack" ]]; then
+                    abort "device family pack already specified"
+                fi
+
+                if [[ "$#" -le 0 ]]; then
+                    abort "device family pack name and version not specified"
+                fi
+
+                if [[ "$#" -le 1 ]]; then
+                    abort "device family pack version not specified"
+                fi
+
+                local -r family_pack_name="$1"; shift
+                local -r family_pack_version="$1"; shift
+
+                local -r family_pack="Atmel.${family_pack_name}_DFP.${family_pack_version}"
+                ;;
             --help)
                 display_help_text
                 exit
@@ -193,7 +198,11 @@ function main()
         abort "'--install-prefix' must be specified"
     fi
 
-    install_device_family_packs
+    if [[ -z "$family_pack" ]]; then
+        abort "'--family-pack' must be specified"
+    fi
+
+    install_device_family_pack
 }
 
 main "$@"
